branches:
  except:
  - /^wip/
language: node_js
sudo: true
addons:
  mariadb: '10.2'
  firefox: 'latest-esr'
node_js:
- '8'
before_install:
- mkdir cvc4/
- wget https://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/cvc4-1.5-x86_64-linux-opt
  -O cvc4/cvc4
- chmod +x cvc4/cvc4
- mkdir geckodriver/
- wget https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux64.tar.gz
- tar xvf geckodriver-v0.22.0-linux64.tar.gz -C geckodriver/
- export PATH="`pwd`/cvc4:`pwd`/geckodriver:$PATH"
- sudo apt-get update -q -y
install:
- sudo apt-get install -y graphicsmagick libcairo2-dev libpango1.0-dev libgif-dev realpath
- yarn
before_script:
- mysql -u root -e "create database if not exists thingengine_test; grant all privileges on thingengine_test.* to 'thingengine'@'%' identified by 'thingengine';"
script:
- yarn lint
- yarn test
after_success: yarn run coverage