branches:
  except:
  - /^wip/
language: node_js
sudo: true
node_js:
- '8'
before_install:
- sudo apt-get update -q -y
install:
- sudo apt-get install -y graphicsmagick libcairo2-dev libpango1.0-dev libgif-dev
script:
- yarn lint
