version: '3'
services:
  web:
    build: .
    ports:
      - 3000:8080
    depends_on:
      - db
    environment:
      DATABASE_URL: 'mysql://thingengine:thingengine@localhost/thingengine?charset=utf8mb4_bin'
      SECRET_KEY: dev
      JWT_SIGNING_KEY: dev
      AES_SECRET_KEY: dev
  db:
    image: mariadb/server:10.4
    volumes:
      - mariadb_data:/var/lib/mariadb
    environment:
      MARIADB_ROOT_HOST: localhost
      MARIADB_ROOT_PASSWORD: thingengine
      MARIADB_DATABASE: thingengine
      MARIADB_USER: thingengine
      MARIADB_PASSWORD: thingengine
    ports:
      - 3306:3306
volumes:
  mariadb_data:
