apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "training-deployment"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "training"
    spec:
      containers:
      - name: "training"
        image: ${REPO}/almond/training:v0.7
        imagePullPolicy: Always
        command:
          - /bin/bash
          - /var/lib/almond-training/startup.sh
          - run-training
          - "--port"
          - 9999
        ports:
        - containerPort: 9999
        volumeMounts:
        - name: config
          mountPath: "/etc/almond-cloud"
          readOnly: true
        - name: aws
          mountPath: "/home/almond-prod/.aws"
          readOnly: true
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
              - NET_ADMIN
      volumes:
      - name: config
        secret:
          secretName: almond-config
      - name: aws
        secret:
          secretName: aws-config
