apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "gpu-training-deployment"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "gpu-training"
    spec:
      containers:
      - name: "gpu-training"
        image: ${REPO}/almond/training:v0.7
        imagePullPolicy: Always
        command:
          - /bin/bash
          - /var/lib/almond-training/startup.sh
          - run-gpu-training
        resources:
          limits:
              nvidia.com/gpu: 1
        volumeMounts:
        - name: config
          mountPath: "/etc/almond-cloud"
          readOnly: true
        - name: aws
          mountPath: "/home/almond-prod/.aws"
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: almond-config
      - name: aws
        secret:
          secretName: aws-config
