apiVersion: apps/v1
kind: Deployment
metadata:
  name: "almond-frontend"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "almond-frontend"
  template:
    metadata:
      labels:
        app: "almond-frontend"
    spec:
      containers:
      - name: "main"
        image: stanfordoval/almond-cloud:latest
        args: ["run-frontend"]
        volumeMounts:
        - name: config
          mountPath: "/etc/almond-cloud"
          readOnly: true
        resources:
          requests:
            memory: 8G
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
      volumes:
      - name: config
        secret:
          secretName: almond-config
---
apiVersion: v1
kind: Service
metadata:
  name: almond-frontend
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: almond-frontend
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: almond-frontend
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: almond-frontend
          servicePort: 8080

