apiVersion: apps/v1
kind: Deployment
metadata:
  name: "gpu-training"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "gpu-training"
  template:
    metadata:
      labels:
        app: "gpu-training"
    spec:
      containers:
      - name: "gpu-training"
        image: stanfordoval/almond-cloud:latest-decanlp-cuda
        imagePullPolicy: Always
        command: ["run-gpu-training"]
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: config
          mountPath: "/etc/almond-cloud"
          readOnly: true
        - name: aws
          mountPath: "/home/almond-prod/.aws"
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: almond-config
      - name: aws
        secret:
          secretName: aws-config
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
