apiVersion: apps/v1
kind: Deployment
metadata:
  name: "training"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "training"
  template:
    metadata:
      labels:
        app: "training"
    spec:
      containers:
      - name: "training"
        image: stanfordoval/almond-cloud:latest-decanlp
        imagePullPolicy: Always
        args: ["run-training"]
        volumeMounts:
        - name: config
          mountPath: "/etc/almond-cloud"
          readOnly: true
        - name: aws
          mountPath: "/home/almond-cloud/.aws"
          readOnly: true
        - name: training-config
          mountPath: "/etc/almond-cloud/training"
          readOnly: true
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
              - NET_ADMIN
        resources:
          requests:
            memory: 32G
            ephemeral-storage: 40G
        readinessProbe:
          tcpSocket:
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 20
      volumes:
      - name: config
        secret:
          secretName: almond-config
      - name: aws
        secret:
          secretName: aws-config
      - name: training-config
        configMap:
          name: training-config
---
apiVersion: v1
kind: Service
metadata:
  name: "training"
spec:
  ports:
  - port: 8090
    protocol: TCP
  selector:
    app: "training"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: training-config
data:
  training.conf.json: |-
    {
      "train_iterations": 50000,
      "save_every": 2000,
      "val_every": 1000,
      "log_every": 500,
      "trainable_decoder_embedding": 50,
      "no_glove_decoder": true,
      "synthetic_depth": 5,
      "no_commit": true
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: training-config-small
data:
  training.conf.json: |-
    {
      "train_iterations": 100,
      "save_every": 50,
      "val_every": 50,
      "log_every": 10,
      "trainable_decoder_embedding": 50,
      "no_glove_decoder": true,
      "synthetic_depth": 2,
      "no_commit": true
    }

